#!/bin/bash
#shellchecker
#coded by : ./MimiUndetected
#mimiUndetected[at]gmail.com
#request any tools ?
NC='\033[0m'
GREEN='\e[38;5;82m'
CYAN='\e[38;5;45m'
RED='\e[38;5;196m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'
ngegad(){
	for cek in $(cat $bd); do
		#edit uu=kata yang mau di grep
			uu=Uname
			ceuk=$(curl -sN $cek | grep -o $uu)
			if [ "$ceuk" = "Uname" ]; then
				echo "$cek" >> ada.txt
				printf "${GREEN}$cek -> masih ada${NC}\n"
			else
				printf "${RED}$cek -> NotFound :( \n${NC}"
			fi
		done
}
 header(){
printf "${GREEN}"
printf "    ___        __                _____ _____ _____   _       ________                \n"
printf "        ____  __ _           _   _    _           _      _            _           _  \n"
printf "       / /  \/  (_)         (_) | |  | |         | |    | |          | |         | | \n"
printf "      / /| \  / |_ _ __ ___  _  | |  | |_ __   __| | ___| |_ ___  ___| |_ ___  __| | \n"
printf "     / / | |\/| | | '_ ` _ \| | | |  | | '_ \ / _` |/ _ \ __/ _ \/ __| __/ _ \/ _` | \n"
printf "  _ / /  | |  | | | | | | | | | | |__| | | | | (_| |  __/ ||  __/ (__| ||  __/ (_| | \n"
printf " (_)_/   |_|  |_|_|_| |_| |_|_|  \____/|_| |_|\__,_|\___|\__\___|\___|\__\___|\__,_| \n"                                                                                  
printf "     Mass Shell Checker By ./MimiUndetected ======================= Run Dulu Baru Nanya  \n"
printf "${NC}\n"
}
clear
header
echo "_________________________________________________"
echo "File pada directory ini : "
ls
echo "_________________________________________________"
echo -n "Masukan nama file backdoor yang mau di check : "
read bd 
if [ ! -f $bd ]; then
	echo "MASUKIN NYA YANG BENER LO KIRA INI ANAL ?"
else
	sleep 4
ngegad

fi
